In [18]:
import pandas as pd
import numpy as np

## 1. 预设变量

In [19]:
!pip install openpyxl

In [20]:
file_01_path = "./附件1.xlsx"
data = pd.read_excel(file_01_path, sheet_name=0,usecols=[0,2,3])
ss = data.head()
print(ss)

   进车顺序  动力  驱动
0     1  燃油  两驱
1     2  混动  两驱
2     3  混动  两驱
3     4  燃油  两驱
4     5  混动  两驱


In [21]:
df_li = data.values.tolist()
df_li[0]


[1, '燃油', '两驱']

In [22]:
len(df_li)

318

In [23]:
for i in range(len(df_li)):
    if df_li[i][1]=='燃油':
        df_li[i][1]=0
    else:
        df_li[i][1]=1

    if df_li[i][2]=='两驱':
        df_li[i][2]=0
    else:
        df_li[i][2]=1
df_li

[[1, 0, 0],
 [2, 1, 0],
 [3, 1, 0],
 [4, 0, 0],
 [5, 1, 0],
 [6, 0, 0],
 [7, 0, 0],
 [8, 0, 0],
 [9, 1, 0],
 [10, 1, 0],
 [11, 0, 0],
 [12, 0, 0],
 [13, 1, 0],
 [14, 1, 0],
 [15, 1, 0],
 [16, 0, 0],
 [17, 1, 0],
 [18, 1, 0],
 [19, 1, 0],
 [20, 1, 0],
 [21, 0, 0],
 [22, 0, 1],
 [23, 0, 0],
 [24, 1, 0],
 [25, 1, 0],
 [26, 0, 1],
 [27, 1, 0],
 [28, 0, 0],
 [29, 1, 0],
 [30, 0, 0],
 [31, 0, 1],
 [32, 0, 0],
 [33, 1, 0],
 [34, 1, 0],
 [35, 0, 1],
 [36, 1, 0],
 [37, 1, 0],
 [38, 1, 0],
 [39, 1, 0],
 [40, 1, 0],
 [41, 1, 0],
 [42, 1, 0],
 [43, 0, 1],
 [44, 1, 0],
 [45, 0, 1],
 [46, 1, 0],
 [47, 1, 0],
 [48, 1, 0],
 [49, 1, 0],
 [50, 1, 0],
 [51, 0, 0],
 [52, 0, 0],
 [53, 1, 0],
 [54, 0, 0],
 [55, 1, 0],
 [56, 0, 0],
 [57, 0, 0],
 [58, 0, 0],
 [59, 1, 0],
 [60, 0, 0],
 [61, 1, 0],
 [62, 0, 0],
 [63, 1, 0],
 [64, 0, 1],
 [65, 1, 0],
 [66, 0, 0],
 [67, 1, 0],
 [68, 0, 0],
 [69, 1, 0],
 [70, 0, 0],
 [71, 1, 0],
 [72, 0, 0],
 [73, 1, 0],
 [74, 1, 0],
 [75, 1, 0],
 [76, 1, 0],
 [77, 1, 0],
 [78, 1,

In [24]:
num_JinCheDao = 6
num_CheWei = 10
PBS = np.zeros(shape=(7,10))

PBS_entracne = 0
PBS_exit = 3
PBS_JieCheJi = 1
PBS_SongCheJi = 2

JinCheJi_free = 1
SongCheJi_free = 1

JinCheDao_free = np.ones(num_JinCheDao)

PBS_index = np.zeros(shape=((7,10)))
for i in range(7):
    for j in range(10):
        PBS_index[i,j] =int(str(i+1)+str(j+1))

# 进车道中各个车位的间隔
PBS_interval = np.zeros([7,9*2])
PBS_total = np.zeros([7,10+9*2])
print(PBS_index)
print(PBS_interval)
print(PBS_total)

[[ 11.  12.  13.  14.  15.  16.  17.  18.  19. 110.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29. 210.]
 [ 31.  32.  33.  34.  35.  36.  37.  38.  39. 310.]
 [ 41.  42.  43.  44.  45.  46.  47.  48.  49. 410.]
 [ 51.  52.  53.  54.  55.  56.  57.  58.  59. 510.]
 [ 61.  62.  63.  64.  65.  66.  67.  68.  69. 610.]
 [ 71.  72.  73.  74.  75.  76.  77.  78.  79. 710.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [25]:
Songche_time = Jieche_time = [18,12,6,0,12,18]
Songche_Fan_time = Jieche_Fan_time = [24,18,12,6,12,18]

In [26]:
rank_JinCheDao = [3,2,1,4,0,5]

priority_JinCheDao = [4,3,2,1,3,4]
for i in range(num_JinCheDao):
    priority_JinCheDao[i] -= 1
priority_JinCheDao

[3, 2, 1, 0, 2, 3]

In [27]:
Sequence_JinChe  = np.array(df_li)
Sequence_JinChe.shape
C = Sequence_JinChe.shape[0]
T = 10000
print(C)

318


In [28]:
CT_matrix = np.zeros([C,T], dtype= int)-1
print(CT_matrix.shape)
CT_matrix


(318, 10000)


array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [29]:
# C=318
time_CheShen = np.zeros(C)
time_JieChe = 0
time_Songche = 0
# 设置接车机和送车机的时间与空闲对应序列
time_free_SongCheJi = np.ones(T)
time_free_JieCheJi = np.ones(T)

In [30]:
# 判断当前车型和当前车道在动力类型方面的匹配度
def judge_Dongli_CheDao(dongli_type,JinCheDao_index):
    feikong_sequence = []
    for j in range(num_CheWei-1,-1,-1):
        if PBS[JinCheDao_index][j]!=0:
            feikong_sequence.append(PBS[JinCheDao_index][j])
    if dongli_type== 0 and feikong_sequence[0]==1:
        return True
    elif len(feikong_sequence)>1 and dongli_type== 0 and feikong_sequence[0]==0 and feikong_sequence[1]==1:
        return True
    elif len(feikong_sequence)>2 and dongli_type== 0 and feikong_sequence[0]== 0 and feikong_sequence[1]== 0 and feikong_sequence[2]==1:
        return True
    elif len(feikong_sequence)>3 and dongli_type== 0 and feikong_sequence[0]== 1 and feikong_sequence[1]== 0 and feikong_sequence[2]==0 and feikong_sequence[3]==1:
        return True
    else:
        return False

    

In [31]:
# 先做出来再说
def Choose_path(time,Id_Cheshen,current_ID):
    # 先判断各个道是否为空,若均为空，则直接进入第四车道
    if np.all(JinCheDao_free == 1):
        if JinCheJi_free == 1:
            # 第四条进车道不为空
            # 该车身的位置发生变化，CT_matrix填入该车身的序号,PBS中填入该车身序号
            JinCheDao_free[3]=0
            CT_matrix[Id_Cheshen][time]=PBS_index[rank_JinCheDao[0]][num_CheWei-1]#410
            PBS[rank_JinCheDao[0]][num_CheWei-1]=Id_Cheshen
            # 直接判断当前个体的未来走向,沿着当前道路继续走，直到走到PBS_exit
            for i in range(1,num_CheWei):
                CT_matrix[Id_Cheshen][time+9*i] = PBS_index[3][num_CheWei-i]
            CT_matrix[Id_Cheshen][time+9*9] = PBS_exit
    # 若有车道不为空，依次判断该序列的后三个个体是否满足规则1“两个混动之间”夹两个非混动”
    # 
    elif JinCheJi_free == 1:
        # 提取当前的动力类型是混动还是非混动
            dongli_type = df_li[Id_Cheshen-1][1]            
            # 先判断是否有可以匹配的非空闲序列，若有则直接填入，否则判断是否有空闲车道，有则填入，没有则按优先级进行选择
            for i in range(len(rank_JinCheDao)):
                if (JinCheDao_free[rank_JinCheDao[i]] == 0) and judge_Dongli_CheDao(dongli_type,rank_JinCheDao[i]):
                    # 当前车道匹配
                    break
    
            


In [32]:
'''
1. 判断送车机是否空闲
2. 判断进车道各车位是否可以前进(前方车位是否为空)
3. 判断接车机是否空闲

'''


Sequence_CHUCHE = []

def CheShen_out_of_PBS(CheDao_index,time_current,row_index):
    # CheShen_out_of_PBS:
    # PBS_total[CheDao_index][0] = 0
    Sequence_CHUCHE.append(row_index)
    if CheDao_index != 4:
        CT_matrix[row_index, time_current + Songche_time[CheDao_index - 1] / 2] = PBS_SongCheJi
        CT_matrix[row_index, time_current + Songche_time[CheDao_index - 1]] = PBS_exit
    else:
        CT_matrix[row_index, time_current] = PBS_exit
        time_free_SongCheJi[time_current]=1

time_current  = 0
# 设置双指针，分别指向当前要处理的车身和下一个要处理的车身
soldier_current = 0
soldier_next = 1
'''
while time_current <T:
    # 1. 先判断送车机是否空闲
    if time_free_SongCheJi[time_current]==1:
        if np.sum(CT_matrix[:,time_current]!=0)>0:
            time_free_SongCheJi[time_current]=0
            if np.sum(CT_matrix[:,time_current])==1:
                row_index = np.nonzero(CT_matrix[:,time_current])[0][0]
                col_index = np.nonzero(CT_matrix[:,time_current])[1][0]
                CheDao_index = int(str(CT_matrix[row_index][col_index])[0])
                CheShen_out_of_PBS(CheDao_index,time_current,row_index)
            elif np.sum(CT_matrix[:,time_current]) > 1:
                row_index_array = np.nonzero(CT_matrix[:,time_current])[0]
                col_index_array= np.nonzero(CT_matrix[:,time_current])[1]
                CheDao_index_array = np.array([int(str(CT_matrix[i][j])[0]) for (i,j) in zip(row_index_array,col_index_array)])
                for i in range(len(rank_JinCheDao)):
                    for j in range(len(CheDao_index_array)):
                        if rank_JinCheDao[i] == CheDao_index_array[j]:
                            row_index = row_index_array[j]
                            CheDao_index = CheDao_index_array[j]
                            CheShen_out_of_PBS(CheDao_index,time_current,row_index)
    # 如果此时送车机不为空闲，则意味着正在运送车辆
 
    # 2. 更新PBS_total
    '''
    从PBS_total的1号车道开始迭代
    '''
    for i in range(num_JinCheDao):
        for j in range(PBS_total.shape[1]-1):
            if PBS_total[i][j]==0 and PBS_total[i][j+1]!=0:
                PBS_total[i][j]=PBS_total[i][j+1]
                PBS_total[i][j+1]=0
    for i in range(PBS_total.shape[1]):
        pass
    

    # 3. 检查
    if time_free_JieCheJi[time_current]==1:
        pass
        
    time_current += 3
'''

IndentationError: unexpected indent (2927387268.py, line 51)

In [ ]:
# 计算最短时间模型的得分

def Compute_Seq_Scores(Seqence):
    scores_total = np.zeros(4)+100
    dongli_type_list = []
    qudong_type_list = []

    for i in range(len(Seqence)):
        dongli_type_list.append(Sequence_JinChe[Seqence[i]][1])


    for i in range(len(Seqence)):
        qudong_type_list.append(Sequence_JinChe[Seqence[i]][2])

    # 计算第一个分数
    flag_1 = 0
    hundong_index = []
    for i in range(len(dongli_type_list)):
        if dongli_type_list[i]==1 :
            hundong_index.append(i)

    for i in range(len(hundong_index)-1):
        if(hundong_index[i+1]-hundong_index[i]!=2):
            scores_total[0]-=1
        
    # 计算第二个分数
    block_total_list = []
    i = 0
    
    jiange_point = [] # 元素均为分块的起点
    jiange_point.append(0)
    qudong_first = qudong_type_list[0]
    for j in range(i+1,len(qudong_type_list)):
        if qudong_type_list[j] == qudong_first and (qudong_type_list[j-1]!=qudong_first):
            jiange_point.append(j)
    
    

    print(jiange_point)
    jiange_point.append(len(qudong_type_list))
    for i in range(len(jiange_point)-1):
        block_current = []
        for j in range(jiange_point[i],jiange_point[i+1]):
            block_current.append(qudong_type_list[j])

        block_total_list.append(block_current)
    print(block_total_list)
    print(len(block_total_list))

    for i in range(len(block_total_list)):
        block_cur = block_total_list[i]
        block_first = block_cur[0]
        block_last = block_cur[len(block_cur)-1]


        if len(block_cur)%2!=0:
            scores_total[1]-1
        else:
            block_first = block_cur[0]
            block_last = block_cur[len(block_cur)-1]
            if block_first==block_last:
                scores_total[1] -= 1
                continue

            for j in range(len(block_cur)):
                if(j<len(block_cur)/2) and block_cur[j]!=block_first:
                    scores_total[1] -= 1
                    break
                elif j>=len(block_cur)/2 and block_cur[j]!=block_last:
                    scores_total[1] -= 1
                    break
        
    scores_total[2]=100
    scores_total[3]=100-0.01*(9*C+72)
    print(qudong_type_list)
    print(scores_total[0])
    print(scores_total[1])
    print(scores_total[0]*0.4+scores_total[1]*0.3+scores_total[2]*0.2+scores_total[3]*0.1)
Compute_Seq_Scores([i for i in range(318)])


[0, 22, 26, 31, 35, 43, 45, 64, 100, 106, 134, 142, 203, 226, 228, 231, 254, 266, 268, 270, 272, 285, 288, 312]
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1], [0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 1], [0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1], [0, 1], [0, 1], [0, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [42]:
CT_matrix.shape
time_current = 0

first_index = 0
second_index = 1
# while time_current<T:
#     if time_current == 0:
#         CT_matrix[Sequence_JinChe[first_index]]=410
#         CT_matrix[Sequence_JinChe[second_index]]= PBS_entracne

for i in range(len(Sequence_JinChe)):
    for j in range(10):
        if j<9:
            CT_matrix[Sequence_JinChe[i]][time_current+9*j]= PBS_index[rank_JinCheDao[0]][num_CheWei-j-1]
        else:
            CT_matrix[Sequence_JinChe[i]][time_current+9*j] = PBS_exit
    time_current = time_current+9
        


IndexError: index 9 is out of bounds for axis 0 with size 3